#!/usr/bin/env bash

install() {
  link "$REPOSITORY_ROOT" "${XDG_CONFIG_HOME:-$HOME/.config}/alacritty"
  pip install --user alacritty-colorscheme
}

post_remove_hook() {
  pip uninstall alacritty-colorscheme
}

source <(curl -Lfs https://git.io/lnkr)
